services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=${DB_NAME}'
      - 'POSTGRES_PASSWORD=${DB_PASSWORD}'
      - 'POSTGRES_USER=${DB_USERNAME}'
    ports:
      - '5432:5432'
    volumes:
      - ./postsData:/var/lib/postgresql/posts_project
volumes:
  postsData: